# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ojalá fuera informático, V2
email: frodo_gv@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Este es un blog en el que puedes encontrar soluciones simples a problemas comunes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://frodo45127.github.io" # the base hostname & protocol for your site
twitter_username: Frodo45127
github_username:  Frodo45127

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /posts/:categories/:title/

# Gems
gems:
  - jekyll-sitemap # Sitemap generation with the official gem
  - jekyll-redirect-from # Redirect pages in case I change them
  - jekyll-feed # Generate a feed (no more feed.xml in root)

# Files excluded from site generation
# exclude:
# - README.md
