# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ojalá fuera informático, V2
description: 'Este es un blog en el que puedes encontrar soluciones simples a problemas comunes.'
url: 'https://frodo45127.github.io' # the base hostname & protocol for your site
baseurl: '' # the subpath of your site, e.g. /blog
google_analytics: 'UA-70766983-1'
disqus_shortname: 'frodo45127-github'

author:
  name: Frodo45127
  email: frodo_gv@hotmail.com
  twitter: Frodo45127
  github_username: Frodo45127

twitter:
  username: Frodo45127

defaults:
  -
    scope:
      path: '_posts'
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /post/:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate', 'jekyll-seo-tag']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
